### ISSUE TITLE
The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00./stringify?commonjs-require'

### ISSUE THREAD

**Issue by ahjsrhj** [MinatoHikari/vite-plugin-filesystem-multi-pages#2]
因为英语比较差，所以就不用机翻英语描述问题了。
在启用这个插件之后，引入qs这个包，里面用到了require()语法去导入(其它包内用到这种语法的也是)，构建时会报错。
日志如下:
```
[vite:load-fallback] Could not load ./stringify?commonjs-require (imported by node_modules/.pnpm/qs@6.10.3/node_modules/qs/lib/index.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00./stringify?commonjs-require'
error during build:
TypeError [PLUGIN_ERROR]: Could not load ./stringify?commonjs-require (imported by node_modules/.pnpm/qs@6.10.3/node_modules/qs/lib/index.js): The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00./stringify?commonjs-require'
    at open (node:internal/fs/promises:450:10)
    at Object.readFile (node:internal/fs/promises:795:20)
    at Object.load (/Users/xxx/Works/base/test/test-vite-vue3/node_modules/.pnpm/vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:41120:38)
    at async /Users/xxx/Works/base/test/test-vite-vue3/node_modules/.pnpm/rollup@2.61.0/node_modules/rollup/dist/shared/rollup.js:22109:83
    at async Queue.work (/Users/xxx/Works/base/test/test-vite-vue3/node_modules/.pnpm/rollup@2.61.0/node_modules/rollup/dist/shared/rollup.js:21681:32)
```

**Comment by MinatoHikari** [comment]
应该可以了
fixed in 0.3.4

**Comment by ahjsrhj** [comment]
感谢处理。
新版本在启用All-in-one template 模式时会报错：
```
Could not resolve entry module (src/pages/activity/index.html).
error during build:
Error: Could not resolve entry module (src/pages/activity/index.html).
    at error (/Users/xxx/Works/base/vue3-mpa-h5-template/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/Users/xxx/Works/base/vue3-mpa-h5-template/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:22631:20)
    at async Promise.all (index 0)
```
不使用该模式则一切正常

**Comment by MinatoHikari** [comment]
我试了下没问题，你是不是没在template里面替换src
整个复现的sandbox最好
@ahjsrhj

> 感谢处理。 新版本在启用All-in-one template 模式时会报错：
> 
> ```
> Could not resolve entry module (src/pages/activity/index.html).
> error during build:
> Error: Could not resolve entry module (src/pages/activity/index.html).
>     at error (/Users/xxx/Works/base/vue3-mpa-h5-template/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:198:30)
>     at ModuleLoader.loadEntryModule (/Users/xxx/Works/base/vue3-mpa-h5-template/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:22631:20)
>     at async Promise.all (index 0)
> ```
> 
> 不使用该模式则一切正常

**Comment by ahjsrhj** [comment]
样例在这里：https://github.com/ahjsrhj/vue3-mpa-fmp-temp
运行npm run dev正常，npm run build会报错
尝试过修改 publicTemplateSrc 为 path.resolve(__dirname, 'index.html') 或者 './index.html' 均会报错

**Comment by MinatoHikari** [comment]
> 样例在这里：https://github.com/ahjsrhj/vue3-mpa-fmp-temp 运行npm run dev正常，npm run build会报错 尝试过修改 publicTemplateSrc 为 path.resolve(__dirname, 'index.html') 或者 './index.html' 均会报错

这个是不能和pages一起用的
